import { Router } from 'express';
import propertyRouter from '../modules/property/property.router';
import unitRouter from '../modules/unit/unit.router';
import unitTypeRouter from '../modules/unit_type/unit_type.router';
import leaseRouter from '../modules/lease/lease.router';
import rentalApplicationRouter from '../modules/rental_application/rental_application.router';
import peopleRouter from '../modules/people';
import authRouter from '../modules/auth/auth.router';
import { authenticateToken } from '../middleware/auth.middleware';
import serviceRequestRouter from '../modules/service_request/service_request.router';
import workOrderRouter from '../modules/work_order/work_order.router';
import inspectionRouter from '../modules/inspection/inspection.router';
import inventoryRouter from '../modules/inventory/inventory.router';
import fixedAssetRouter from '../modules/fixed_asset/fixed_asset.router';
import propertyUtilityBillingRouter from '../modules/property_utility_billing/property_utility_billing.router';
import propertyLateFeePolicyRouter from '../modules/property_late_fee_policy/property_late_fee_policy.router';
import propertyAttachmentRouter from '../modules/property_attachment/property_attachment.router';
import propertyLeaseTemplateAttachmentRouter from '../modules/property_lease_template_attachment/property_lease_template_attachment.router';
import propertyLeaseRenewalAttachmentRouter from '../modules/property_lease_renewal_attachment/property_lease_renewal_attachment.router';
import propertyPhotoRouter from '../modules/property_photo/property_photo.router';
import propertyUpcomingActivityRouter from '../modules/property_upcoming_activity/property_upcoming_activity.router';
import propertyOwnerRouter from '../modules/property_owner/property_owner.router';
import rentableItemRouter from '../modules/rentable_item/rentable_item.router';
import userRouter from '../modules/user/user.router';
import unitUpcomingActivityRouter from '../modules/unit_upcoming_activity/unit_upcoming_activity.router';
import unitPhotoRouter from '../modules/unit_photo/unit_photo.router';
import unitTypePhotoRouter from '../modules/unit_type_photo/unit_type_photo.router';
import unitTypeAmenityRouter from '../modules/unit_type_amenity/unit_type_amenity.router';
import leaseTemplateRouter from '../modules/lease_template/lease_template.router';
import secondaryTenantRouter from '../modules/secondary_tenant/secondary_tenant.router';
import rentalApplicationTemplateRouter from '../modules/rental_application_template/rental_application_template.router';
import applicantRouter from '../modules/applicant/applicant.router';
import rentalApplicationEmergencyContactRouter from '../modules/rental_application_emergency_contact/rental_application_emergency_contact.router';
import rentalApplicationResidentialHistoryRouter from '../modules/rental_application_residential_history/rental_application_residential_history.router';
import rentalApplicationFinancialInformationRouter from '../modules/rental_application_financial_information/rental_application_financial_information.router';
import rentalApplicationAdditionalIncomeRouter from '../modules/rental_application_additional_income/rental_application_additional_income.router';
import rentalApplicationDependentRouter from '../modules/rental_application_dependent/rental_application_dependent.router';
import rentalApplicationPetsRouter from '../modules/rental_application_pets/rental_application_pets.router';
import rentalApplicationAttachmentRouter from '../modules/rental_application_attachment/rental_application_attachment.router';
import tenantUpcomingActivityRouter from '../modules/tenant_upcoming_activity/tenant_upcoming_activity.router';
import tenantAttachmentRouter from '../modules/tenant_attachment/tenant_attachment.router';
import vendorTypeRouter from '../modules/vendor_type/vendor_type.router';
import vendorAddressRouter from '../modules/vendor_address/vendor_address.router';
import vendorAttachmentRouter from '../modules/vendor_attachment/vendor_attachment.router';
import ownerUpcomingActivityRouter from '../modules/owner_upcoming_activity/owner_upcoming_activity.router';
import serviceRequestAttachmentRouter from '../modules/service_request_attachment/service_request_attachment.router';
import laborRouter from '../modules/labor/labor.router';
import areaRouter from '../modules/area/area.router';
import areaItemRouter from '../modules/area_item/area_item.router';
import projectExpenseRouter from '../modules/project_expense/project_expense.router';
import projectExpenseAttachmentRouter from '../modules/project_expense_attachment/project_expense_attachment.router';
import purchaseOrderRouter from '../modules/purchase_order/purchase_order.router';
import purchaseOrderItemRouter from '../modules/purchase_order_item/purchase_order_item.router';
import purchaseOrderAttachmentRouter from '../modules/purchase_order_attachment/purchase_order_attachment.router';
import projectRouter from '../modules/project/project.router';

const router = Router();

router.use('/authentication', authRouter);

// Apply authentication middleware to all routes below this point
router.use(authenticateToken);

router.use('/properties', propertyRouter);
router.use('/units', unitRouter);
router.use('/unit-types', unitTypeRouter);
router.use('/leases', leaseRouter);
router.use('/rental-applications', rentalApplicationRouter);
router.use('/people', peopleRouter);
router.use('/users', userRouter);
router.use('/service-requests', serviceRequestRouter);
router.use('/work-orders', workOrderRouter);
router.use('/inspections', inspectionRouter);
router.use('/inventory', inventoryRouter);
router.use('/fixed-assets', fixedAssetRouter);
router.use('/property-upcoming-activities', propertyUpcomingActivityRouter);
router.use('/property-utility-billings', propertyUtilityBillingRouter);
router.use('/property-late-fee-policies', propertyLateFeePolicyRouter);
router.use('/property-attachments', propertyAttachmentRouter);
router.use('/property-lease-template-attachments', propertyLeaseTemplateAttachmentRouter);
router.use('/property-lease-renewal-attachments', propertyLeaseRenewalAttachmentRouter);
router.use('/property-photos', propertyPhotoRouter);
router.use('/property-owners', propertyOwnerRouter);
router.use('/rentable-items', rentableItemRouter);
router.use('/unit-upcoming-activities', unitUpcomingActivityRouter);
router.use('/unit-photos', unitPhotoRouter);
router.use('/unit-type-photos', unitTypePhotoRouter);
router.use('/unit-type-amenities', unitTypeAmenityRouter);
router.use('/lease-templates', leaseTemplateRouter);
router.use('/secondary-tenants', secondaryTenantRouter);
router.use('/rental-application-templates', rentalApplicationTemplateRouter);
router.use('/applicants', applicantRouter);
router.use('/rental-application-emergency-contacts', rentalApplicationEmergencyContactRouter);
router.use('/rental-application-residential-histories', rentalApplicationResidentialHistoryRouter);
router.use('/rental-application-financial-information', rentalApplicationFinancialInformationRouter);
router.use('/rental-application-additional-income', rentalApplicationAdditionalIncomeRouter);
router.use('/rental-application-dependents', rentalApplicationDependentRouter);
router.use('/rental-application-pets', rentalApplicationPetsRouter);
router.use('/rental-application-attachments', rentalApplicationAttachmentRouter);
router.use('/tenant-upcoming-activities', tenantUpcomingActivityRouter);
router.use('/tenant-attachments', tenantAttachmentRouter);
router.use('/vendor-types', vendorTypeRouter);
router.use('/vendor-addresses', vendorAddressRouter);
router.use('/vendor-attachments', vendorAttachmentRouter);
router.use('/owner-upcoming-activities', ownerUpcomingActivityRouter);
router.use('/service-request-attachments', serviceRequestAttachmentRouter);
router.use('/labors', laborRouter);
router.use('/areas', areaRouter);
router.use('/area-items', areaItemRouter);
router.use('/project-expenses', projectExpenseRouter);
router.use('/project-expense-attachments', projectExpenseAttachmentRouter);
router.use('/purchase-orders', purchaseOrderRouter);
router.use('/purchase-order-items', purchaseOrderItemRouter);
router.use('/purchase-order-attachments', purchaseOrderAttachmentRouter);
router.use('/projects', projectRouter);

export default router;
